title: SIT111 Hardware Module Development
description: Complete Repository for SIT111 Deakin University Hardware Module


remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

gem "github-pages", group: :jekyll_plugins
